// Generated from data/card-translations.csv. Do not edit this file by hand.
window.CARD_TRANSLATIONS = {
  "10": {
    "zh-TW": {
      "name": "豺狼人獵頭者",
      "subtitle": "荒原追獵者",
      "abilities": [
        {
          "title": "登場｜獵首標記",
          "text": "對一名已受傷的敵方怪獸造成 2 點傷害。"
        }
      ]
    },
    "en": {
      "name": "Gnoll Headhunter",
      "subtitle": "Wasteland Tracker",
      "abilities": [
        {
          "title": "On Play | Marked Prey",
          "text": "Deal 2 damage to a wounded enemy."
        }
      ]
    },
    "ja": {
      "name": "ノールの首狩り",
      "subtitle": "荒野の追跡者",
      "abilities": [
        {
          "title": "登場｜狩りの印",
          "text": "傷を負った敵1体に2ダメージを与える。"
        }
      ]
    },
    "ko": {
      "name": "놀 머리사냥꾼",
      "subtitle": "황야의 추적자",
      "abilities": [
        {
          "title": "등장 | 사냥의 표식",
          "text": "다친 적 하나에게 피해를 2 줍니다."
        }
      ]
    }
  },
  "11": {
    "zh-TW": {
      "name": "空心樹人",
      "subtitle": "古林空殼",
      "abilities": [
        {
          "title": "被動｜嘲諷",
          "text": "敵方必須優先攻擊此怪獸。"
        },
        {
          "title": "被動｜老樹新生",
          "text": "你的回合開始時，恢復自身 1 點血量。"
        }
      ]
    },
    "en": {
      "name": "Hollow Treant",
      "subtitle": "Ancient Husk",
      "abilities": [
        {
          "title": "Passive | Taunt",
          "text": "Enemies must attack this monster first."
        },
        {
          "title": "Passive | Old Growth",
          "text": "At the start of your turn, restore 1 Health to itself."
        }
      ]
    },
    "ja": {
      "name": "空洞のトレント",
      "subtitle": "古森の抜け殻",
      "abilities": [
        {
          "title": "常時｜挑発",
          "text": "敵はこのモンスターを優先して攻撃しなければならない。"
        },
        {
          "title": "常時｜老樹の再生",
          "text": "自分のターン開始時、自身の体力を1回復する。"
        }
      ]
    },
    "ko": {
      "name": "속 빈 나무정령",
      "subtitle": "고대 숲의 껍질",
      "abilities": [
        {
          "title": "지속 | 도발",
          "text": "적은 이 몬스터를 우선 공격해야 합니다."
        },
        {
          "title": "지속 | 고목의 재생",
          "text": "내 턴 시작 시 자신의 생명력을 1 회복합니다."
        }
      ]
    }
  },
  "12": {
    "zh-TW": {
      "name": "月蛾妖精",
      "subtitle": "銀翼織夢者",
      "abilities": [
        {
          "title": "登場｜月粉迷夢",
          "text": "使一名敵方怪獸的戰鬥值降低 2 點，持續至你的下個回合開始。"
        }
      ]
    },
    "en": {
      "name": "Moonmoth Fae",
      "subtitle": "Silverwing Dreamweaver",
      "abilities": [
        {
          "title": "On Play | Moon Dust",
          "text": "Give an enemy -2 Attack until the start of your next turn."
        }
      ]
    },
    "ja": {
      "name": "月蛾の妖精",
      "subtitle": "銀翼の夢織り",
      "abilities": [
        {
          "title": "登場｜月粉の夢",
          "text": "敵1体の攻撃力を次の自分のターン開始時まで−2する。"
        }
      ]
    },
    "ko": {
      "name": "달나방 요정",
      "subtitle": "은빛 날개 꿈술사",
      "abilities": [
        {
          "title": "등장 | 달가루의 꿈",
          "text": "내 다음 턴 시작까지 적 하나의 공격력을 2 감소시킵니다."
        }
      ]
    }
  },
  "13": {
    "zh-TW": {
      "name": "魚人潮汐祭司",
      "subtitle": "迴潮祈者",
      "abilities": [
        {
          "title": "登場｜回潮治癒",
          "text": "使所有友方怪獸恢復 1 點血量。"
        },
        {
          "title": "被動｜潮汐祝禱",
          "text": "你的回合結束時，使自身恢復 1 點血量。"
        }
      ]
    },
    "en": {
      "name": "Murloc Tide Priest",
      "subtitle": "Returning Tide",
      "abilities": [
        {
          "title": "On Play | Tidal Healing",
          "text": "Restore 1 Health to all allies."
        },
        {
          "title": "Passive | Tide Prayer",
          "text": "At the end of your turn, restore 1 Health to itself."
        }
      ]
    },
    "ja": {
      "name": "マーロックの潮司祭",
      "subtitle": "返し潮の祈り手",
      "abilities": [
        {
          "title": "登場｜潮の癒やし",
          "text": "味方全体の体力を1回復する。"
        },
        {
          "title": "常時｜潮の祈り",
          "text": "自分のターン終了時、自身の体力を1回復する。"
        }
      ]
    },
    "ko": {
      "name": "멀록 파도 사제",
      "subtitle": "돌아오는 파도의 기도자",
      "abilities": [
        {
          "title": "등장 | 밀물의 치유",
          "text": "모든 아군의 생명력을 1 회복합니다."
        },
        {
          "title": "지속 | 파도의 기도",
          "text": "내 턴 종료 시 자신의 생명력을 1 회복합니다."
        }
      ]
    }
  },
  "14": {
    "zh-TW": {
      "name": "蟹甲角鬥士",
      "subtitle": "鉗鋒鬥將",
      "abilities": [
        {
          "title": "登場｜甲殼防禦",
          "text": "獲得 3 點護盾，優先抵擋傷害。"
        }
      ]
    },
    "en": {
      "name": "Crab Gladiator",
      "subtitle": "Clawblade Champion",
      "abilities": [
        {
          "title": "On Play | Shell Guard",
          "text": "Gain 3 Shield, which absorbs damage first."
        }
      ]
    },
    "ja": {
      "name": "蟹殻の剣闘士",
      "subtitle": "鋏刃の闘将",
      "abilities": [
        {
          "title": "登場｜甲殻の守り",
          "text": "ダメージを優先して吸収するシールド3を得る。"
        }
      ]
    },
    "ko": {
      "name": "게껍질 검투사",
      "subtitle": "집게날의 투사",
      "abilities": [
        {
          "title": "등장 | 갑각 방어",
          "text": "피해를 먼저 흡수하는 보호막 3을 얻습니다."
        }
      ]
    }
  },
  "15": {
    "zh-TW": {
      "name": "沉船寄居怪",
      "subtitle": "殘骸背負者",
      "abilities": [
        {
          "title": "被動｜嘲諷",
          "text": "敵方必須優先攻擊此怪獸。"
        },
        {
          "title": "登場｜殘船護殼",
          "text": "獲得 2 點護盾，優先抵擋傷害。"
        }
      ]
    },
    "en": {
      "name": "Shipwreck Hermit",
      "subtitle": "Wreckage Bearer",
      "abilities": [
        {
          "title": "Passive | Taunt",
          "text": "Enemies must attack this monster first."
        },
        {
          "title": "On Play | Wreck Shell",
          "text": "Gain 2 Shield, which absorbs damage first."
        }
      ]
    },
    "ja": {
      "name": "難破船のヤドカリ",
      "subtitle": "残骸を背負う者",
      "abilities": [
        {
          "title": "常時｜挑発",
          "text": "敵はこのモンスターを優先して攻撃しなければならない。"
        },
        {
          "title": "登場｜残骸の殻",
          "text": "ダメージを優先して吸収するシールド2を得る。"
        }
      ]
    },
    "ko": {
      "name": "난파선 소라게",
      "subtitle": "잔해를 짊어진 자",
      "abilities": [
        {
          "title": "지속 | 도발",
          "text": "적은 이 몬스터를 우선 공격해야 합니다."
        },
        {
          "title": "등장 | 난파선 껍질",
          "text": "피해를 먼저 흡수하는 보호막 2를 얻습니다."
        }
      ]
    }
  },
  "16": {
    "zh-TW": {
      "name": "溺亡水手",
      "subtitle": "幽潮歸客",
      "abilities": [
        {
          "title": "登場｜冰冷拖曳",
          "text": "使一名敵方怪獸的戰鬥值降低 1 點，持續至你的下個回合開始。"
        }
      ]
    },
    "en": {
      "name": "Drowned Sailor",
      "subtitle": "Ghost-Tide Wanderer",
      "abilities": [
        {
          "title": "On Play | Icy Drag",
          "text": "Give an enemy -1 Attack until the start of your next turn."
        }
      ]
    },
    "ja": {
      "name": "溺れた船乗り",
      "subtitle": "幽潮の帰還者",
      "abilities": [
        {
          "title": "登場｜冷たい引き波",
          "text": "敵1体の攻撃力を次の自分のターン開始時まで−1する。"
        }
      ]
    },
    "ko": {
      "name": "익사한 선원",
      "subtitle": "유령 파도의 귀환자",
      "abilities": [
        {
          "title": "등장 | 차가운 끌어당김",
          "text": "내 다음 턴 시작까지 적 하나의 공격력을 1 감소시킵니다."
        }
      ]
    }
  },
  "17": {
    "zh-TW": {
      "name": "礁岩海妖",
      "subtitle": "碎浪歌者",
      "abilities": [
        {
          "title": "登場｜惑心歌聲",
          "text": "使一名敵方怪獸無法攻擊，持續至你的下個回合開始。"
        }
      ]
    },
    "en": {
      "name": "Reef Siren",
      "subtitle": "Wavebreaker Singer",
      "abilities": [
        {
          "title": "On Play | Beguiling Song",
          "text": "An enemy cannot attack until the start of your next turn."
        }
      ]
    },
    "ja": {
      "name": "岩礁のセイレーン",
      "subtitle": "砕け波の歌い手",
      "abilities": [
        {
          "title": "登場｜惑わす歌",
          "text": "敵1体は次の自分のターン開始時まで攻撃できない。"
        }
      ]
    },
    "ko": {
      "name": "암초의 세이렌",
      "subtitle": "부서진 파도의 가수",
      "abilities": [
        {
          "title": "등장 | 유혹의 노래",
          "text": "적 하나가 내 다음 턴 시작까지 공격할 수 없습니다."
        }
      ]
    }
  },
  "18": {
    "zh-TW": {
      "name": "灰燼獵犬",
      "subtitle": "燼野追蹤者",
      "abilities": [
        {
          "title": "被動｜突襲",
          "text": "登場的回合即可攻擊。"
        },
        {
          "title": "被動｜餘火",
          "text": "被擊敗時，對一名敵方怪獸造成 1 點傷害。"
        }
      ]
    },
    "en": {
      "name": "Ash Hound",
      "subtitle": "Ember Tracker",
      "abilities": [
        {
          "title": "Passive | Rush",
          "text": "Can attack on the turn it enters play."
        },
        {
          "title": "Passive | Embers",
          "text": "When defeated, deal 1 damage to an enemy."
        }
      ]
    },
    "ja": {
      "name": "灰燼の猟犬",
      "subtitle": "残り火の追跡者",
      "abilities": [
        {
          "title": "常時｜急襲",
          "text": "登場したターンに攻撃できる。"
        },
        {
          "title": "常時｜残り火",
          "text": "倒された時、敵1体に1ダメージを与える。"
        }
      ]
    },
    "ko": {
      "name": "잿빛 사냥개",
      "subtitle": "잿불 추적자",
      "abilities": [
        {
          "title": "지속 | 급습",
          "text": "등장한 턴에 공격할 수 있습니다."
        },
        {
          "title": "지속 | 남은 불씨",
          "text": "쓰러지면 적 하나에게 피해를 1 줍니다."
        }
      ]
    }
  },
  "19": {
    "zh-TW": {
      "name": "鏡面魅魔",
      "subtitle": "映魂惑使",
      "abilities": [
        {
          "title": "被動｜鏡面反射",
          "text": "每回合第一次受到攻擊後，對攻擊者造成 2 點傷害。"
        }
      ]
    },
    "en": {
      "name": "Mirror Succubus",
      "subtitle": "Soul Reflection",
      "abilities": [
        {
          "title": "Passive | Mirror Reflect",
          "text": "After being attacked for the first time each turn, deal 2 damage to the attacker."
        }
      ]
    },
    "ja": {
      "name": "鏡のサキュバス",
      "subtitle": "魂映しの惑い手",
      "abilities": [
        {
          "title": "常時｜鏡の反射",
          "text": "毎ターン最初に攻撃を受けた後、攻撃者に2ダメージを与える。"
        }
      ]
    },
    "ko": {
      "name": "거울 서큐버스",
      "subtitle": "영혼을 비추는 유혹자",
      "abilities": [
        {
          "title": "지속 | 거울 반사",
          "text": "매 턴 처음 공격받은 후 공격자에게 피해를 2 줍니다."
        }
      ]
    }
  },
  "20": {
    "zh-TW": {
      "name": "硫磺公爵",
      "subtitle": "煉獄貴胄",
      "abilities": [
        {
          "title": "登場｜硫火敕令",
          "text": "對所有敵方怪獸造成 2 點傷害。"
        },
        {
          "title": "被動｜公爵威儀",
          "text": "你的回合結束時，使另一名友方怪獸獲得 1 點護盾。"
        }
      ]
    },
    "en": {
      "name": "Sulfur Duke",
      "subtitle": "Infernal Noble",
      "abilities": [
        {
          "title": "On Play | Sulfur Decree",
          "text": "Deal 2 damage to all enemies."
        },
        {
          "title": "Passive | Ducal Presence",
          "text": "At the end of your turn, give another ally 1 Shield."
        }
      ]
    },
    "ja": {
      "name": "硫黄の公爵",
      "subtitle": "煉獄の貴族",
      "abilities": [
        {
          "title": "登場｜硫火の勅令",
          "text": "敵全体に2ダメージを与える。"
        },
        {
          "title": "常時｜公爵の威光",
          "text": "自分のターン終了時、他の味方1体にシールド1を付与する。"
        }
      ]
    },
    "ko": {
      "name": "유황 공작",
      "subtitle": "연옥의 귀족",
      "abilities": [
        {
          "title": "등장 | 유황불 칙령",
          "text": "모든 적에게 피해를 2 줍니다."
        },
        {
          "title": "지속 | 공작의 위엄",
          "text": "내 턴 종료 시 다른 아군 하나에게 보호막 1을 부여합니다."
        }
      ]
    }
  },
  "21": {
    "zh-TW": {
      "name": "鐐銬獄卒",
      "subtitle": "鐵牢看守",
      "abilities": [
        {
          "title": "被動｜嘲諷",
          "text": "敵方必須優先攻擊此怪獸。"
        },
        {
          "title": "登場｜鎖鏈束縛",
          "text": "使一名敵方怪獸的戰鬥值降低 2 點，持續至你的下個回合開始。"
        }
      ]
    },
    "en": {
      "name": "Shackle Jailer",
      "subtitle": "Iron Prison Guard",
      "abilities": [
        {
          "title": "Passive | Taunt",
          "text": "Enemies must attack this monster first."
        },
        {
          "title": "On Play | Chain Bind",
          "text": "Give an enemy -2 Attack until the start of your next turn."
        }
      ]
    },
    "ja": {
      "name": "鎖の獄卒",
      "subtitle": "鉄牢の番人",
      "abilities": [
        {
          "title": "常時｜挑発",
          "text": "敵はこのモンスターを優先して攻撃しなければならない。"
        },
        {
          "title": "登場｜鎖の束縛",
          "text": "敵1体の攻撃力を次の自分のターン開始時まで−2する。"
        }
      ]
    },
    "ko": {
      "name": "족쇄 간수",
      "subtitle": "철창의 파수꾼",
      "abilities": [
        {
          "title": "지속 | 도발",
          "text": "적은 이 몬스터를 우선 공격해야 합니다."
        },
        {
          "title": "등장 | 사슬 속박",
          "text": "내 다음 턴 시작까지 적 하나의 공격력을 2 감소시킵니다."
        }
      ]
    }
  },
  "22": {
    "zh-TW": {
      "name": "石化雞蛇",
      "subtitle": "凝視災禽",
      "abilities": [
        {
          "title": "被動｜石化凝視",
          "text": "此怪獸攻擊後，使目標無法攻擊，持續至你的下個回合開始。"
        }
      ]
    },
    "en": {
      "name": "Cockatrice",
      "subtitle": "Dread Gaze",
      "abilities": [
        {
          "title": "Passive | Petrifying Gaze",
          "text": "After this monster attacks, its target cannot attack until the start of your next turn."
        }
      ]
    },
    "ja": {
      "name": "コカトリス",
      "subtitle": "災いの眼差し",
      "abilities": [
        {
          "title": "常時｜石化の視線",
          "text": "攻撃した後、その対象は次の自分のターン開始時まで攻撃できない。"
        }
      ]
    },
    "ko": {
      "name": "코카트리스",
      "subtitle": "재앙의 시선",
      "abilities": [
        {
          "title": "지속 | 석화의 시선",
          "text": "공격한 후 대상이 내 다음 턴 시작까지 공격할 수 없습니다."
        }
      ]
    }
  },
  "23": {
    "zh-TW": {
      "name": "寶箱擬態怪",
      "subtitle": "貪金伏噬者",
      "abilities": [
        {
          "title": "被動｜伏擊利齒",
          "text": "每回合第一次受到攻擊後，對攻擊者造成 2 點傷害。"
        }
      ]
    },
    "en": {
      "name": "Chest Mimic",
      "subtitle": "Gold-Hungry Ambusher",
      "abilities": [
        {
          "title": "Passive | Ambush Fangs",
          "text": "After being attacked for the first time each turn, deal 2 damage to the attacker."
        }
      ]
    },
    "ja": {
      "name": "宝箱のミミック",
      "subtitle": "黄金を狙う伏兵",
      "abilities": [
        {
          "title": "常時｜待ち伏せの牙",
          "text": "毎ターン最初に攻撃を受けた後、攻撃者に2ダメージを与える。"
        }
      ]
    },
    "ko": {
      "name": "보물상자 미믹",
      "subtitle": "황금을 노리는 복병",
      "abilities": [
        {
          "title": "지속 | 매복 송곳니",
          "text": "매 턴 처음 공격받은 후 공격자에게 피해를 2 줍니다."
        }
      ]
    }
  },
  "24": {
    "zh-TW": {
      "name": "矮人精靈",
      "subtitle": "符石鍛造師",
      "abilities": [
        {
          "title": "登場｜符石護甲",
          "text": "獲得 2 點護盾，優先抵擋傷害。"
        },
        {
          "title": "戰吼｜鍛造之力",
          "text": "使另一名友方怪獸獲得 +1 戰鬥值。"
        }
      ]
    },
    "en": {
      "name": "Dwarf Elf",
      "subtitle": "Runestone Smith",
      "abilities": [
        {
          "title": "On Play | Rune Armor",
          "text": "Gain 2 Shield that blocks damage first."
        },
        {
          "title": "Battlecry | Forge Power",
          "text": "Give an ally +1 Attack."
        }
      ]
    },
    "ja": {
      "name": "ドワーフエルフ",
      "subtitle": "ルーン石の鍛冶師",
      "abilities": [
        {
          "title": "登場｜ルーンの鎧",
          "text": "ダメージを優先して吸収するシールド2を得る。"
        },
        {
          "title": "雄叫び｜鍛造の力",
          "text": "他の味方1体の攻撃力を＋1する。"
        }
      ]
    },
    "ko": {
      "name": "드워프 엘프",
      "subtitle": "룬석 대장장이",
      "abilities": [
        {
          "title": "등장 | 룬 갑옷",
          "text": "피해를 먼저 흡수하는 보호막 2를 얻습니다."
        },
        {
          "title": "전투의 함성 | 제련의 힘",
          "text": "다른 아군 하나의 공격력을 +1 증가시킵니다."
        }
      ]
    }
  },
  "25": {
    "zh-TW": {
      "name": "克蘇魯",
      "subtitle": "深淵沉睡者",
      "abilities": [
        {
          "title": "登場｜深淵低語",
          "text": "使所有敵方怪獸的戰鬥值降低 2 點，持續至你的下個回合開始。"
        },
        {
          "title": "被動｜古神再生",
          "text": "你的回合開始時，恢復自身 2 點血量。"
        }
      ]
    },
    "en": {
      "name": "Cthulhu",
      "subtitle": "Abyssal Sleeper",
      "abilities": [
        {
          "title": "On Play | Abyss Whisper",
          "text": "Give all enemies -2 Attack until the start of your next turn."
        },
        {
          "title": "Passive | Old God Renewal",
          "text": "At the start of your turn, restore 2 Health to itself."
        }
      ]
    },
    "ja": {
      "name": "クトゥルフ",
      "subtitle": "深淵の眠り手",
      "abilities": [
        {
          "title": "登場｜深淵の囁き",
          "text": "敵全体の攻撃力を次の自分のターン開始時まで−2する。"
        },
        {
          "title": "常時｜古神の再生",
          "text": "自分のターン開始時、自身の体力を2回復する。"
        }
      ]
    },
    "ko": {
      "name": "크툴루",
      "subtitle": "심연의 잠든 자",
      "abilities": [
        {
          "title": "등장 | 심연의 속삭임",
          "text": "내 다음 턴 시작까지 모든 적의 공격력을 2 감소시킵니다."
        },
        {
          "title": "지속 | 고대 신의 재생",
          "text": "내 턴 시작 시 자신의 생명력을 2 회복합니다."
        }
      ]
    }
  },
  "26": {
    "zh-TW": {
      "name": "維京狂戰士",
      "subtitle": "血怒雙斧",
      "abilities": [
        {
          "title": "被動｜浴血狂怒",
          "text": "自身血量為 4 點以下時，戰鬥值增加 3 點。"
        },
        {
          "title": "戰吼｜破盾猛擊",
          "text": "登場時，移除一名敵方怪獸的護盾。"
        }
      ]
    },
    "en": {
      "name": "Viking Berserker",
      "subtitle": "Bloodrage Axes",
      "abilities": [
        {
          "title": "Passive | Blood Fury",
          "text": "While this monster has 4 Health or less, it has +3 Attack."
        },
        {
          "title": "Battlecry | Shieldbreaker",
          "text": "On entering play, remove an enemy's Shield."
        }
      ]
    },
    "ja": {
      "name": "ヴァイキングの狂戦士",
      "subtitle": "血怒の双斧",
      "abilities": [
        {
          "title": "常時｜血の怒り",
          "text": "自身の体力が4以下の間、攻撃力が＋3される。"
        },
        {
          "title": "雄叫び｜盾砕き",
          "text": "登場時、敵1体のシールドを取り除く。"
        }
      ]
    },
    "ko": {
      "name": "바이킹 광전사",
      "subtitle": "피의 분노 쌍도끼",
      "abilities": [
        {
          "title": "지속 | 피의 분노",
          "text": "자신의 생명력이 4 이하인 동안 공격력이 +3 증가합니다."
        },
        {
          "title": "전투의 함성 | 방패 파괴",
          "text": "등장 시 적 하나의 보호막을 제거합니다."
        }
      ]
    }
  },
  "27": {
    "zh-TW": {
      "name": "精靈使女",
      "subtitle": "晨露侍者",
      "abilities": [
        {
          "title": "登場｜晨露恩澤",
          "text": "使一名友方怪獸恢復 3 點血量。"
        },
        {
          "title": "被動｜靈葉守護",
          "text": "你的回合結束時，使另一名友方怪獸獲得 1 點護盾。"
        }
      ]
    },
    "en": {
      "name": "Elven Handmaiden",
      "subtitle": "Dew Attendant",
      "abilities": [
        {
          "title": "On Play | Morning Dew",
          "text": "Restore 3 Health to an ally."
        },
        {
          "title": "Passive | Spirit Leaves",
          "text": "At the end of your turn, give another ally 1 Shield."
        }
      ]
    },
    "ja": {
      "name": "エルフの侍女",
      "subtitle": "朝露の侍者",
      "abilities": [
        {
          "title": "登場｜朝露の恵み",
          "text": "味方1体の体力を3回復する。"
        },
        {
          "title": "常時｜霊葉の守護",
          "text": "自分のターン終了時、他の味方1体にシールド1を付与する。"
        }
      ]
    },
    "ko": {
      "name": "엘프 시녀",
      "subtitle": "아침 이슬의 시종",
      "abilities": [
        {
          "title": "등장 | 아침 이슬의 은혜",
          "text": "아군 하나의 생명력을 3 회복합니다."
        },
        {
          "title": "지속 | 정령 잎의 수호",
          "text": "내 턴 종료 시 다른 아군 하나에게 보호막 1을 부여합니다."
        }
      ]
    }
  },
  "28": {
    "zh-TW": {
      "name": "護盾石像鬼",
      "subtitle": "不動壁壘",
      "abilities": [
        {
          "title": "被動｜嘲諷",
          "text": "敵方必須優先攻擊此怪獸。"
        },
        {
          "title": "登場｜石化護盾",
          "text": "獲得 3 點護盾，優先抵擋傷害。"
        }
      ]
    },
    "en": {
      "name": "Shield Gargoyle",
      "subtitle": "Unyielding Bulwark",
      "abilities": [
        {
          "title": "Passive | Taunt",
          "text": "Enemies must attack this monster first."
        },
        {
          "title": "On Play | Stone Shield",
          "text": "Gain 3 Shield, which absorbs damage first."
        }
      ]
    },
    "ja": {
      "name": "盾のガーゴイル",
      "subtitle": "不動の砦",
      "abilities": [
        {
          "title": "常時｜挑発",
          "text": "敵はこのモンスターを優先して攻撃しなければならない。"
        },
        {
          "title": "登場｜石の盾",
          "text": "ダメージを優先して吸収するシールド3を得る。"
        }
      ]
    },
    "ko": {
      "name": "방패 가고일",
      "subtitle": "흔들리지 않는 보루",
      "abilities": [
        {
          "title": "지속 | 도발",
          "text": "적은 이 몬스터를 우선 공격해야 합니다."
        },
        {
          "title": "등장 | 돌의 보호막",
          "text": "피해를 먼저 흡수하는 보호막 3을 얻습니다."
        }
      ]
    }
  },
  "29": {
    "zh-TW": {
      "name": "地獄火巨人",
      "subtitle": "熔核焚世者",
      "abilities": [
        {
          "title": "登場｜地獄烈焰",
          "text": "對所有敵方怪獸造成 2 點傷害。"
        },
        {
          "title": "被動｜熔火反噬",
          "text": "受到攻擊後，對攻擊者造成 1 點傷害。"
        }
      ]
    },
    "en": {
      "name": "Hellfire Giant",
      "subtitle": "Molten Worldburner",
      "abilities": [
        {
          "title": "On Play | Hellfire",
          "text": "Deal 2 damage to all enemies."
        },
        {
          "title": "Passive | Molten Reprisal",
          "text": "After being attacked, deal 1 damage to the attacker."
        }
      ]
    },
    "ja": {
      "name": "地獄炎の巨人",
      "subtitle": "溶岩の滅世者",
      "abilities": [
        {
          "title": "登場｜地獄の炎",
          "text": "敵全体に2ダメージを与える。"
        },
        {
          "title": "常時｜溶岩の反撃",
          "text": "攻撃を受けた後、攻撃者に1ダメージを与える。"
        }
      ]
    },
    "ko": {
      "name": "지옥불 거인",
      "subtitle": "용암의 세계파괴자",
      "abilities": [
        {
          "title": "등장 | 지옥의 화염",
          "text": "모든 적에게 피해를 2 줍니다."
        },
        {
          "title": "지속 | 용암의 반격",
          "text": "공격받은 후 공격자에게 피해를 1 줍니다."
        }
      ]
    }
  },
  "30": {
    "zh-TW": {
      "name": "雷霆薩滿法師",
      "subtitle": "雷霆喚靈者",
      "abilities": [
        {
          "title": "登場｜雷霆震擊",
          "text": "對一名敵方怪獸造成 3 點傷害。"
        },
        {
          "title": "被動｜祖靈祝福",
          "text": "你的回合結束時，使一名友方怪獸恢復 1 點血量。"
        }
      ]
    },
    "en": {
      "name": "Thunder Shaman",
      "subtitle": "Stormcaller",
      "abilities": [
        {
          "title": "On Play | Thunderstrike",
          "text": "Deal 3 damage to an enemy."
        },
        {
          "title": "Passive | Ancestral Gift",
          "text": "At the end of your turn, restore 1 Health to an ally."
        }
      ]
    },
    "ja": {
      "name": "雷のシャーマン",
      "subtitle": "雷霊の呼び手",
      "abilities": [
        {
          "title": "登場｜雷撃",
          "text": "敵1体に3ダメージを与える。"
        },
        {
          "title": "常時｜祖霊の祝福",
          "text": "自分のターン終了時、味方1体の体力を1回復する。"
        }
      ]
    },
    "ko": {
      "name": "천둥 주술사",
      "subtitle": "천둥 정령 소환사",
      "abilities": [
        {
          "title": "등장 | 천둥 강타",
          "text": "적 하나에게 피해를 3 줍니다."
        },
        {
          "title": "지속 | 선조의 축복",
          "text": "내 턴 종료 시 아군 하나의 생명력을 1 회복합니다."
        }
      ]
    }
  },
  "31": {
    "zh-TW": {
      "name": "火蜥蜴圖騰",
      "subtitle": "熾焰守望者",
      "abilities": [
        {
          "title": "被動｜餘燼脈動",
          "text": "你的回合結束時，對一名敵方怪獸造成 1 點傷害。"
        },
        {
          "title": "被動｜火靈庇護",
          "text": "你的回合開始時，使另一名友方怪獸獲得 1 點護盾。"
        }
      ]
    },
    "en": {
      "name": "Fire Salamander Totem",
      "subtitle": "Blazing Watcher",
      "abilities": [
        {
          "title": "Passive | Ember Pulse",
          "text": "At the end of your turn, deal 1 damage to an enemy."
        },
        {
          "title": "Passive | Fire Spirit Ward",
          "text": "At the start of your turn, give another ally 1 Shield."
        }
      ]
    },
    "ja": {
      "name": "火蜥蜴のトーテム",
      "subtitle": "炎の見張り",
      "abilities": [
        {
          "title": "常時｜残火の鼓動",
          "text": "自分のターン終了時、敵1体に1ダメージを与える。"
        },
        {
          "title": "常時｜火霊の庇護",
          "text": "自分のターン開始時、他の味方1体にシールド1を付与する。"
        }
      ]
    },
    "ko": {
      "name": "불도마뱀 토템",
      "subtitle": "불꽃의 감시자",
      "abilities": [
        {
          "title": "지속 | 잿불의 맥동",
          "text": "내 턴 종료 시 적 하나에게 피해를 1 줍니다."
        },
        {
          "title": "지속 | 불 정령의 가호",
          "text": "내 턴 시작 시 다른 아군 하나에게 보호막 1을 부여합니다."
        }
      ]
    }
  },
  "01": {
    "zh-TW": {
      "name": "魚人酋長",
      "subtitle": "潮鱗統領",
      "abilities": [
        {
          "title": "登場｜部族號令",
          "text": "使另一名友方怪獸獲得 +2 戰鬥值，持續至回合結束。"
        },
        {
          "title": "被動｜潮鱗護衛",
          "text": "你的回合結束時，使另一名友方怪獸獲得 1 點護盾。"
        }
      ]
    },
    "en": {
      "name": "Murloc Chief",
      "subtitle": "Tidescale Commander",
      "abilities": [
        {
          "title": "On Play | Tribal Command",
          "text": "Give another ally +2 Attack until the end of the turn."
        },
        {
          "title": "Passive | Tidescale Guard",
          "text": "At the end of your turn, give another ally 1 Shield."
        }
      ]
    },
    "ja": {
      "name": "マーロックの族長",
      "subtitle": "潮鱗の統率者",
      "abilities": [
        {
          "title": "登場｜部族の号令",
          "text": "他の味方1体の攻撃力をターン終了時まで＋2する。"
        },
        {
          "title": "常時｜潮鱗の守護",
          "text": "自分のターン終了時、他の味方1体にシールド1を付与する。"
        }
      ]
    },
    "ko": {
      "name": "멀록 족장",
      "subtitle": "파도비늘 지휘관",
      "abilities": [
        {
          "title": "등장 | 부족의 명령",
          "text": "이번 턴이 끝날 때까지 다른 아군 하나의 공격력을 +2 증가시킵니다."
        },
        {
          "title": "지속 | 파도비늘 수호",
          "text": "내 턴 종료 시 다른 아군 하나에게 보호막 1을 부여합니다."
        }
      ]
    }
  },
  "02": {
    "zh-TW": {
      "name": "骷髏士兵",
      "subtitle": "朽刃守衛",
      "abilities": [
        {
          "title": "被動｜亡骨復起",
          "text": "此怪獸第一次被擊敗時，以 1 點血量復活。"
        }
      ]
    },
    "en": {
      "name": "Skeleton Soldier",
      "subtitle": "Rustblade Guard",
      "abilities": [
        {
          "title": "Passive | Bone Revival",
          "text": "The first time this monster is defeated, revive it with 1 Health."
        }
      ]
    },
    "ja": {
      "name": "骸骨の兵士",
      "subtitle": "朽ち刃の守衛",
      "abilities": [
        {
          "title": "常時｜骨の再生",
          "text": "初めて倒された時、体力1で復活する。"
        }
      ]
    },
    "ko": {
      "name": "해골 병사",
      "subtitle": "녹슨 칼날의 파수꾼",
      "abilities": [
        {
          "title": "지속 | 뼈의 부활",
          "text": "처음 쓰러지면 생명력 1로 부활합니다."
        }
      ]
    }
  },
  "03": {
    "zh-TW": {
      "name": "食屍鬼",
      "subtitle": "墓園飢客",
      "abilities": [
        {
          "title": "被動｜腐宴",
          "text": "此怪獸擊敗敵方怪獸後，恢復自身 2 點血量。"
        }
      ]
    },
    "en": {
      "name": "Ghoul",
      "subtitle": "Graveyard Hunger",
      "abilities": [
        {
          "title": "Passive | Carrion Feast",
          "text": "After this monster defeats an enemy, restore 2 Health to itself."
        }
      ]
    },
    "ja": {
      "name": "グール",
      "subtitle": "墓場の飢餓者",
      "abilities": [
        {
          "title": "常時｜腐肉の宴",
          "text": "敵を倒した後、自身の体力を2回復する。"
        }
      ]
    },
    "ko": {
      "name": "구울",
      "subtitle": "묘지의 굶주림",
      "abilities": [
        {
          "title": "지속 | 부패의 연회",
          "text": "적을 처치한 후 자신의 생명력을 2 회복합니다."
        }
      ]
    }
  },
  "04": {
    "zh-TW": {
      "name": "巨槌大兵",
      "subtitle": "破陣重錘",
      "abilities": [
        {
          "title": "登場｜碎甲重擊",
          "text": "移除一名敵方怪獸的所有護盾。"
        }
      ]
    },
    "en": {
      "name": "Greatmaul Soldier",
      "subtitle": "Linebreaker",
      "abilities": [
        {
          "title": "On Play | Armor Breaker",
          "text": "Remove all Shield from an enemy."
        }
      ]
    },
    "ja": {
      "name": "大槌の兵士",
      "subtitle": "陣形砕き",
      "abilities": [
        {
          "title": "登場｜装甲砕き",
          "text": "敵1体のシールドをすべて取り除く。"
        }
      ]
    },
    "ko": {
      "name": "거대망치 병사",
      "subtitle": "전열 파괴자",
      "abilities": [
        {
          "title": "등장 | 갑옷 파괴",
          "text": "적 하나의 보호막을 모두 제거합니다."
        }
      ]
    }
  },
  "05": {
    "zh-TW": {
      "name": "獨眼雙頭巨人",
      "subtitle": "裂山雙顱",
      "abilities": [
        {
          "title": "被動｜雙顱猛攻",
          "text": "每回合第一次攻擊後，對同一目標再造成 2 點傷害。"
        }
      ]
    },
    "en": {
      "name": "Two-Headed Cyclops",
      "subtitle": "Mountain Splitter",
      "abilities": [
        {
          "title": "Passive | Twin Assault",
          "text": "After its first attack each turn, deal 2 more damage to the same target."
        }
      ]
    },
    "ja": {
      "name": "双頭のサイクロプス",
      "subtitle": "山砕きの双頭",
      "abilities": [
        {
          "title": "常時｜双頭の猛攻",
          "text": "毎ターン最初の攻撃後、同じ対象に追加で2ダメージを与える。"
        }
      ]
    },
    "ko": {
      "name": "쌍두 사이클롭스",
      "subtitle": "산을 가르는 두 머리",
      "abilities": [
        {
          "title": "지속 | 쌍두 맹공",
          "text": "매 턴 첫 공격 후 같은 대상에게 추가로 피해를 2 줍니다."
        }
      ]
    }
  },
  "06": {
    "zh-TW": {
      "name": "地精商人",
      "subtitle": "金袋掮客",
      "abilities": [
        {
          "title": "登場｜奇貨交易",
          "text": "抽 1 張牌。"
        }
      ]
    },
    "en": {
      "name": "Goblin Merchant",
      "subtitle": "Goldpouch Broker",
      "abilities": [
        {
          "title": "On Play | Rare Trade",
          "text": "Draw 1 card."
        }
      ]
    },
    "ja": {
      "name": "ゴブリンの商人",
      "subtitle": "金袋の仲介人",
      "abilities": [
        {
          "title": "登場｜珍品取引",
          "text": "カードを1枚引く。"
        }
      ]
    },
    "ko": {
      "name": "고블린 상인",
      "subtitle": "금주머니 중개인",
      "abilities": [
        {
          "title": "등장 | 진귀한 거래",
          "text": "카드를 1장 뽑습니다."
        }
      ]
    }
  },
  "07": {
    "zh-TW": {
      "name": "赤牙獸人",
      "subtitle": "血誓鬥士",
      "abilities": [
        {
          "title": "被動｜赤牙狂怒",
          "text": "自身血量為 3 點以下時，戰鬥值增加 2 點。"
        }
      ]
    },
    "en": {
      "name": "Redtusk Orc",
      "subtitle": "Bloodsworn Fighter",
      "abilities": [
        {
          "title": "Passive | Redtusk Fury",
          "text": "While this monster has 3 Health or less, it has +2 Attack."
        }
      ]
    },
    "ja": {
      "name": "赤牙のオーク",
      "subtitle": "血誓の戦士",
      "abilities": [
        {
          "title": "常時｜赤牙の怒り",
          "text": "自身の体力が3以下の間、攻撃力が＋2される。"
        }
      ]
    },
    "ko": {
      "name": "붉은엄니 오크",
      "subtitle": "피의 맹세 전사",
      "abilities": [
        {
          "title": "지속 | 붉은엄니의 분노",
          "text": "자신의 생명력이 3 이하인 동안 공격력이 +2 증가합니다."
        }
      ]
    }
  },
  "08": {
    "zh-TW": {
      "name": "鹿角部族薩滿",
      "subtitle": "林靈引路人",
      "abilities": [
        {
          "title": "登場｜林靈恩賜",
          "text": "使一名友方怪獸恢復 3 點血量。"
        },
        {
          "title": "被動｜枝葉庇護",
          "text": "你的回合結束時，使自身獲得 1 點護盾。"
        }
      ]
    },
    "en": {
      "name": "Antler Shaman",
      "subtitle": "Grove Spirit Guide",
      "abilities": [
        {
          "title": "On Play | Forest Gift",
          "text": "Restore 3 Health to an ally."
        },
        {
          "title": "Passive | Leaf Shelter",
          "text": "At the end of your turn, gain 1 Shield."
        }
      ]
    },
    "ja": {
      "name": "鹿角のシャーマン",
      "subtitle": "森霊の案内人",
      "abilities": [
        {
          "title": "登場｜森霊の恵み",
          "text": "味方1体の体力を3回復する。"
        },
        {
          "title": "常時｜木の葉の庇護",
          "text": "自分のターン終了時、自身にシールド1を付与する。"
        }
      ]
    },
    "ko": {
      "name": "사슴뿔 주술사",
      "subtitle": "숲 정령의 길잡이",
      "abilities": [
        {
          "title": "등장 | 숲의 선물",
          "text": "아군 하나의 생명력을 3 회복합니다."
        },
        {
          "title": "지속 | 나뭇잎의 가호",
          "text": "내 턴 종료 시 자신에게 보호막 1을 부여합니다."
        }
      ]
    }
  },
  "09": {
    "zh-TW": {
      "name": "狼騎劫掠者",
      "subtitle": "疾牙掠影",
      "abilities": [
        {
          "title": "被動｜突襲",
          "text": "登場的回合即可攻擊。"
        }
      ]
    },
    "en": {
      "name": "Wolf Raider",
      "subtitle": "Swiftfang Shadow",
      "abilities": [
        {
          "title": "Passive | Rush",
          "text": "Can attack on the turn it enters play."
        }
      ]
    },
    "ja": {
      "name": "狼騎兵の略奪者",
      "subtitle": "疾牙の影",
      "abilities": [
        {
          "title": "常時｜急襲",
          "text": "登場したターンに攻撃できる。"
        }
      ]
    },
    "ko": {
      "name": "늑대 기수 약탈자",
      "subtitle": "날쌘엄니의 그림자",
      "abilities": [
        {
          "title": "지속 | 급습",
          "text": "등장한 턴에 공격할 수 있습니다."
        }
      ]
    }
  }
};
