const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {database}=require('./helpers/d1.cjs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
  const {DB,sqlite}=database();
  const routes={};let translationCalls=0,failTranslation=false,missingTranslationKey=true;
  const googleFetch=async(url,options)=>{translationCalls++;if(failTranslation)return new Response('{}',{status:503});const payload=JSON.parse(options.body);return Response.json({data:{translations:payload.q.map((text,i)=>({translatedText:i===0?payload.target+' translated':text}))}});};
  for(const name of ['admin/translate','admin/translate-product','admin/cards','admin/products','admin/orders','catalog','me','favorites','purchases','my-cards'])routes['/api/'+name]=await import('../functions/api/'+name+'.js');
  const translateRoute=routes['/api/admin/translate'];
  routes['/api/admin/translate']={onRequestPost:[...translateRoute.onRequestPost.slice(0,-1),ctx=>translateRoute.translate(ctx,googleFetch)]};
  const productTranslateRoute=routes['/api/admin/translate-product'];
  routes['/api/admin/translate-product']={onRequestPost:[...productTranslateRoute.onRequestPost.slice(0,-1),ctx=>productTranslateRoute.translateProduct(ctx,googleFetch)]};
  const root=path.resolve(__dirname,'..');
  const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webp':'image/webp'};
  const server=http.createServer(async(req,res)=>{
    try {
      const url=new URL(req.url,'http://127.0.0.1');
      if(routes[url.pathname]){
        const chunks=[];for await(const chunk of req)chunks.push(chunk);
        const request=new Request('http://'+req.headers.host+req.url,{method:req.method,headers:req.headers,body:chunks.length?Buffer.concat(chunks):undefined});
        const fn=routes[url.pathname]['onRequest'+({GET:'Get',POST:'Post',PUT:'Put',DELETE:'Delete'})[req.method]];
        if(!fn){res.writeHead(405).end();return;}
        const handlers=Array.isArray(fn)?fn:[fn];let i=0;
        const context={request,env:{DB,GOOGLE_TRANSLATE_API_KEY:missingTranslationKey?'':'test-secret'},data:{},next:()=>handlers[++i](context)};
        const response=await handlers[0](context);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(await response.text());return;
      }
      const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));
      if(!file.startsWith(root+path.sep)||!types[path.extname(file)]||!fs.existsSync(file)){res.writeHead(404).end();return;}
      res.writeHead(200,{'Content-Type':types[path.extname(file)]});res.end(fs.readFileSync(file));
    }catch(e){res.writeHead(500,{'Content-Type':'application/json'}).end(JSON.stringify({ok:false,error:e.message}));}
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const base='http://127.0.0.1:'+server.address().port;
  const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'msedge'});
  try {
    const context=await browser.newContext();await context.addCookies([{name:'fireside_session',value:'admin-session',url:base}]);
    const page=await context.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});
    page.on('response',async r=>{if(r.url().includes('/api/') && r.status()>=400)console.error(r.status(),await r.text());});
    await page.goto(base+'/admin.html');await page.waitForFunction(()=>document.querySelectorAll('#catalog-body tr').length===31);
    // Display card translations while preserving stored source text and form values.
    const originalName=await page.locator('#catalog-body tr').first().locator('td').first().textContent();
    const originalCatalog=sqlite.prepare('SELECT id,data FROM catalog_cards ORDER BY updated_at DESC,id').all();
    const firstCard=JSON.parse(originalCatalog[0].data);
    await page.locator('#admin-language').selectOption('en');
    assert.equal(await page.locator('html').getAttribute('lang'),'en');
    assert.equal(await page.title(),'Admin | Fireside Cards');
    assert.equal(await page.locator('h1').textContent(),'Admin workspace');
    assert.equal(await page.locator('#search').getAttribute('placeholder'),'Enter keywords');
    assert.equal(await page.locator('#catalog-body tr').first().locator('td').first().textContent(),firstCard.translations.en.name+originalCatalog[0].id);
    const collectionNames={'深海軍團':'Deepsea Legion','荒野之盟':'Wildland Alliance','暗影領域':'Shadow Realm'};
    for(const row of originalCatalog){
      const card=JSON.parse(row.data), rendered=page.locator(`#catalog-body tr:has([data-edit="${row.id}"])`);
      assert.equal(await rendered.locator('td').first().textContent(),card.translations.en.name+row.id);
      assert.ok((await rendered.locator('td').nth(1).textContent()).startsWith(collectionNames[card.collection]));
    }
    assert.match(await page.locator('#count').textContent(),/Showing 31 of 31/);
    await page.locator('#search').fill(firstCard.translations.en.name);
    assert.ok(await page.locator(`[data-edit="${originalCatalog[0].id}"]`).isVisible());
    await page.locator('#admin-language').selectOption('zh-TW');
    assert.ok(await page.locator(`[data-edit="${originalCatalog[0].id}"]`).isVisible());
    await page.locator('#search').fill('');
    assert.equal(await page.locator('#catalog-body tr').first().locator('td').first().textContent(),originalName);
    await page.locator('#admin-language').selectOption('en');
    await page.locator(`[data-edit="${originalCatalog[0].id}"]`).click();
    assert.equal(await page.locator('#edit-form [name="name"]').inputValue(),firstCard.name);
    assert.equal(await page.locator('#edit-form [name="collection"]').inputValue(),firstCard.collection);
    await page.locator('#cancel').click();
    assert.deepEqual(sqlite.prepare('SELECT id,data FROM catalog_cards ORDER BY updated_at DESC,id').all(),originalCatalog);
    assert.equal(translationCalls,0);
    await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#catalog-body tr').length===31);
    assert.equal(await page.locator('#admin-language').inputValue(),'en');
    await page.locator('#create').click();
    assert.equal(await page.locator('#editor-title').textContent(),'Create card');
    assert.equal(await page.locator('#source-language').inputValue(),'zh-TW');
    await page.locator('#edit-form [name="name"]').fill('保持原文');
    await page.locator('#add-ability').click();
    assert.equal(await page.locator('#abilities label').first().textContent(),'Ability name *');
    await page.locator('#translation-panel summary').click();
    await page.locator('#review-translation').click();
    assert.equal(await page.locator('#form-error').textContent(),'Enter a translation first.');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.querySelector('#editor').scrollWidth<=document.querySelector('#editor').clientWidth));
    if(process.env.ADMIN_ENGLISH_SCREENSHOT)await page.screenshot({path:process.env.ADMIN_ENGLISH_SCREENSHOT});
    await page.locator('#cancel').click();
    assert.ok(await page.locator('#unsaved-warning').isVisible());
    assert.equal(await page.locator('#discard-editing').textContent(),'Discard changes and close');
    await page.locator('#discard-editing').click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('[data-tab="products"]').click();
    assert.equal(await page.locator('#list-title').textContent(),'Products & coin prices');
    const bundleNames={'deepsea-duo':'Deepsea Duo Pack','wildland-duo':'Wildland Duo Pack','inferno-duo':'Inferno Duo Pack'};
    for(const [id,name] of Object.entries(bundleNames))assert.equal(await page.locator(`#catalog-body tr:has([data-edit="${id}"]) td`).first().textContent(),name+id);
    await page.locator('#search').fill('Deepsea Duo Pack');
    assert.equal(await page.locator('#catalog-body tr').count(),1);
    await page.locator('#admin-language').selectOption('zh-TW');
    assert.equal(await page.locator('#catalog-body tr td').first().textContent(),'深海雙卡組合deepsea-duo');
    await page.locator('#admin-language').selectOption('en');
    await page.locator('[data-edit="deepsea-duo"]').click();
    assert.equal(await page.locator('#edit-form [name="name"]').inputValue(),'深海雙卡組合');
    await page.locator('#cancel').click();
    await page.locator('#search').fill('深海雙卡組合');
    assert.equal(await page.locator('#catalog-body tr').count(),1);
    await page.locator('#search').fill('');
    const firstProduct=JSON.parse(sqlite.prepare('SELECT data FROM catalog_products ORDER BY updated_at DESC,id LIMIT 1').get().data);
    const included=firstProduct.cardIds.map(id=>JSON.parse(originalCatalog.find(c=>c.id===id).data).translations.en.name);
    for(const name of included)assert.ok((await page.locator('#catalog-body tr').first().locator('td').nth(1).textContent()).includes(name));
    await page.locator('#create').click();
    assert.equal(await page.locator('#editor-title').textContent(),'Create product');
    assert.match(await page.locator('#product-cards').textContent(),/Published/);
    assert.equal(await page.locator(`[data-card-name="${originalCatalog[0].id}"]`).textContent(),firstCard.translations.en.name);
    await page.locator('#cancel').click();
    await page.locator('[data-tab="cards"]').click();
    await page.locator('#search').fill('no-matching-record');
    await page.locator('#admin-language').selectOption('zh-TW');
    assert.equal(await page.locator('#search').inputValue(),'no-matching-record');
    assert.equal(await page.locator('h1').textContent(),'管理工作台');
    await page.locator('#search').fill('');
    await page.setViewportSize({width:1280,height:720});
    await page.locator('#create').click();
    const form=page.locator('#edit-form');
    await page.locator('#cancel').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.locator('#create').click();
    await form.locator('[name="name"]').fill('尚未儲存');
    await page.locator('#close').click();assert.ok(await page.locator('#unsaved-warning').isVisible());
    await page.locator('#keep-editing').click();assert.equal(await form.locator('[name="name"]').inputValue(),'尚未儲存');
    await page.keyboard.press('Escape');assert.ok(await page.locator('#editor').isVisible());assert.ok(await page.locator('#unsaved-warning').isVisible());
    assert.equal(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),true);
    await page.locator('#discard-editing').click();await page.locator('#editor').waitFor({state:'hidden'});
    assert.equal(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),false);
    await page.locator('#create').click();
    for(const [key,value] of Object.entries({id:'browser-card',name:'瀏覽器測試卡',collection:'新系列',image:'cards-clean-layout-31/01-murloc-chief.webp'}))await form.locator(`[name="${key}"]`).fill(value);
    await form.locator('[name="id"]').fill('invalid id');await page.locator('#save').click();
    assert.match(await page.locator('#form-error').textContent(),/無法儲存.*ID/);
    await form.locator('[name="id"]').fill('browser-card');
    await page.locator('#add-ability').click();await page.locator('[data-title]').fill('測試技能');await page.locator('[data-text]').fill('測試規則文字');await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.locator('#search').fill('browser-card');assert.equal(await page.locator('#catalog-body tr').count(),1);
    assert.equal(translationCalls,0);
    assert.match(await page.locator('#notice').textContent(),/已儲存草稿.*自動翻譯未完成/);
    const savedDraft=JSON.parse(sqlite.prepare("SELECT data FROM catalog_cards WHERE id='browser-card'").get().data);
    assert.equal(savedDraft.name,'瀏覽器測試卡');assert.equal(savedDraft.abilities[0].text,'測試規則文字');
    await page.locator('#admin-language').selectOption('en');
    assert.equal(await page.locator('#catalog-body tr td').first().textContent(),'瀏覽器測試卡browser-card');
    assert.ok((await page.locator('#catalog-body tr td').nth(1).textContent()).startsWith('新系列'));
    await page.locator('#admin-language').selectOption('zh-TW');
    await page.locator('[data-edit="browser-card"]').click();
    await page.locator('#translation-panel summary').click();
    missingTranslationKey=false;failTranslation=true;
    await page.locator('#auto-translate').check();await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    assert.match(await page.locator('#notice').textContent(),/已儲存草稿.*自動翻譯未完成/);
    assert.equal(translationCalls,3);failTranslation=false;
    await page.locator('[data-edit="browser-card"]').click();await page.locator('#translation-panel summary').click();
    await page.route('**/api/admin/translate',route=>route.fulfill({status:502,contentType:'text/html',body:'<html>Gateway error</html>'}),{times:1});
    await page.locator('#translate-missing').click();
    await page.waitForFunction(()=>document.querySelector('#form-error').textContent.includes('HTTP 502'));
    assert.match(await page.locator('#form-error').textContent(),/\/api\/admin\/translate/);
    await page.locator('#translate-missing').click();
    await page.waitForFunction(()=>document.querySelector('#translation-status').textContent.includes('自動翻譯'));
    assert.match(await page.locator('#translation-status').textContent(),/自動翻譯/);
    await page.locator('#cancel').click();assert.ok(await page.locator('#unsaved-warning').isVisible());await page.locator('#keep-editing').click();
    await form.locator('[name="translatedName"]').fill('Hand edited English');
    await page.locator('#translate-missing').click();assert.equal(translationCalls,6);
    const reviewAll=async()=>{for(const lang of ['en','ja','ko']){await page.locator('#translation-language').selectOption(lang);await page.locator('#review-translation').click();}};
    await reviewAll();await form.locator('[name="status"]').selectOption('active');await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.locator('[data-edit="browser-card"]').click();await form.locator('[name="name"]').fill('修改後的卡牌');await page.locator('#save').click();
    assert.match(await page.locator('#form-error').textContent(),/草稿/);
    assert.match(await page.locator('#translation-status').textContent(),/原文已更新/);
    assert.equal(await form.locator('[name="translatedName"]').inputValue(),'Hand edited English');
    await reviewAll();await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.locator('[data-edit="browser-card"]').click();await page.locator('#translation-panel summary').click();
    failTranslation=true;page.once('dialog',d=>d.accept());await page.locator('#translate-current').click();
    await page.waitForFunction(()=>document.querySelector('#form-error').textContent.includes('翻譯失敗'));
    assert.equal(await form.locator('[name="translatedName"]').inputValue(),'Hand edited English');failTranslation=false;
    await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.querySelector('#editor').scrollWidth<=document.querySelector('#editor').clientWidth));
    if(process.env.TRANSLATION_SCREENSHOT)await page.screenshot({path:process.env.TRANSLATION_SCREENSHOT});
    await page.locator('#cancel').click();
    await page.locator('[data-tab="products"]').click();await page.locator('#search').fill('');await page.locator('#create').click();
    await form.locator('[name="id"]').fill('browser-product');await form.locator('[name="name"]').fill('測試金幣商品');await form.locator('[name="coinPrice"]').fill('88');await page.locator('#product-cards input[value="browser-card"]').check();
    missingTranslationKey=true;await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    assert.match(await page.locator('#notice').textContent(),/已儲存草稿.*自動翻譯未完成/);
    missingTranslationKey=false;
    await page.locator('[data-edit="browser-product"]').click();await page.locator('#translation-panel summary').click();
    assert.ok(await form.locator('[name="translatedSubtitle"]').isHidden());
    assert.ok(await page.locator('#add-translated-ability').isHidden());
    await page.locator('#translate-missing').click();await page.waitForFunction(()=>document.querySelector('#translation-status').textContent.includes('自動翻譯'));
    await page.locator('#cancel').click();assert.ok(await page.locator('#unsaved-warning').isVisible());await page.locator('#keep-editing').click();
    await form.locator('[name="status"]').selectOption('active');await page.locator('#save').click();assert.match(await page.locator('#form-error').textContent(),/草稿/);
    await form.locator('[name="translatedName"]').fill('Reviewed <Pack>');
    const productTranslationCalls=translationCalls;await page.locator('#translate-missing').click();assert.equal(translationCalls,productTranslationCalls);
    failTranslation=true;page.once('dialog',d=>d.accept());await page.locator('#translate-current').click();
    await page.waitForFunction(()=>document.querySelector('#form-error').textContent.includes('翻譯失敗'));
    assert.equal(await form.locator('[name="translatedName"]').inputValue(),'Reviewed <Pack>');failTranslation=false;
    await reviewAll();
    await form.locator('[name="name"]').fill('修改組合包名稱');await page.locator('#save').click();
    assert.match(await page.locator('#translation-status').textContent(),/原文已更新/);
    assert.match(await page.locator('#form-error').textContent(),/草稿/);
    await form.locator('[name="name"]').fill('測試金幣商品');
    if(process.env.PRODUCT_TRANSLATION_SCREENSHOT){
      await page.locator('#translation-language').selectOption('en');await page.locator('#translate-missing').click();
      await page.locator('#translation-panel').scrollIntoViewIfNeeded();
      assert.ok(await page.evaluate(()=>document.querySelector('#editor').scrollWidth<=document.querySelector('#editor').clientWidth));
      await page.screenshot({path:process.env.PRODUCT_TRANSLATION_SCREENSHOT});
    }
    await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.locator('#admin-language').selectOption('en');
    assert.equal(await page.locator('#catalog-body tr:has([data-edit="browser-product"]) td').first().textContent(),'Reviewed <Pack>browser-product');
    await page.locator('#search').fill('Reviewed');assert.equal(await page.locator('#catalog-body tr').count(),1);await page.locator('#search').fill('');
    await page.locator('#admin-language').selectOption('zh-TW');
    await page.locator('[data-edit="browser-product"]').click();
    assert.equal(await form.locator('[name="translatedName"]').inputValue(),'Reviewed <Pack>');
    assert.match(await page.locator('#translation-status').textContent(),/已人工確認/);
    await page.locator('#product-cards input[value="browser-card"]').uncheck();await page.locator('#cancel').click();assert.ok(await page.locator('#unsaved-warning').isVisible());await page.locator('#keep-editing').click();
    await page.locator('#product-cards input[value="browser-card"]').check();await page.locator('#cancel').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.locator('[data-edit="browser-product"]').click();await form.locator('[name="coinPrice"]').fill('99');
    await page.locator('#close').click();assert.ok(await page.locator('#unsaved-warning').isVisible());await page.locator('#keep-editing').click();
    await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.locator('[data-tab="orders"]').click();await page.locator('#orders-empty').waitFor();assert.match(await page.locator('#order-summary').textContent(),/0/);
    sqlite.exec("INSERT INTO purchase_orders(id,user_id,player_username,player_email,product_id,product_name,currency,unit_price,quantity,total,status,created_at) VALUES ('browser-order',2,'member','member@example.test','browser-product','深海雙卡組合','COIN',88,1,88,'completed','2026-09-21T10:00:00.000Z');");
    await page.locator('#order-search [name="player"]').fill('member');await page.locator('#order-search button').click();await page.waitForFunction(()=>document.querySelectorAll('#orders-body tr').length===1);assert.match(await page.locator('#orders-body').textContent(),/88 金幣/);
    assert.equal(await page.locator('#orders-body strong').textContent(),'ORD-000001');
    assert.equal(await page.locator('#orders-body details small').isVisible(),false);
    await page.locator('#orders-body summary').click();
    assert.equal(await page.locator('#orders-body details small').isVisible(),true);
    assert.equal(await page.locator('#orders-body details small').textContent(),'browser-order');
    await page.locator('#admin-language').selectOption('en');
    assert.match(await page.locator('#orders-body').textContent(),/88 coins/);
    assert.match(await page.locator('#orders-body').textContent(),/Completed/);
    assert.equal(await page.locator('#order-summary').textContent(),'Total transactions: 1');
    assert.equal(await page.locator('#orders-body tr td').nth(2).textContent(),'Deepsea Duo Packbrowser-product');
    assert.equal(sqlite.prepare("SELECT product_name FROM purchase_orders WHERE id='browser-order'").get().product_name,'深海雙卡組合');
    assert.equal(await page.locator('#order-search [name="player"]').inputValue(),'member');
    await page.locator('#admin-language').selectOption('zh-TW');
    assert.equal(await page.locator('#orders-body tr td').nth(2).textContent(),'深海雙卡組合browser-product');
    await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('[data-tab="cards"]').click();await page.locator('#search').fill('');
    if(process.env.ADMIN_SCREENSHOT)await page.screenshot({path:process.env.ADMIN_SCREENSHOT});
    if(process.env.ADMIN_DESKTOP_SCREENSHOT){await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:process.env.ADMIN_DESKTOP_SCREENSHOT});}
    await page.goto(base+'/shop.html');await page.waitForFunction(()=>document.querySelectorAll('.shop-card').length===4);assert.match(await page.locator('.shop-card').filter({hasText:'測試金幣商品'}).textContent(),/99 金幣/);
    await page.selectOption('#language','en');await page.locator('.shop-card').filter({hasText:'Reviewed <Pack>'}).waitFor();
    await page.locator('.shop-card-open[data-bundle="browser-product"]').click();
    assert.ok((await page.locator('#shop-detail').textContent()).includes('Reviewed <Pack>'));
    await page.keyboard.press('Escape');await page.selectOption('#language','zh-TW');
    assert.ok(await page.locator('.shop-buy').first().isEnabled());
    await page.goto(base+'/index.html');await page.waitForFunction(()=>window.CARDS.some(c=>c.id==='browser-card'));await page.locator('#search').fill('修改後的卡牌');assert.equal(await page.locator('#cards .card').count(),1);
    await page.locator('#cards .card').click();await page.waitForFunction(()=>!document.querySelector('#favorite-control button').disabled);await page.locator('#favorite-control button').click();await page.waitForFunction(()=>document.querySelector('#favorite-control button').getAttribute('aria-pressed')==='true');
    await page.goto(base+'/admin.html');await page.waitForFunction(()=>document.querySelectorAll('#catalog-body tr').length===32);await page.locator('[data-edit="browser-card"]').click();await form.locator('[name="status"]').selectOption('archived');await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
    await page.goto(base+'/shop.html');await page.waitForFunction(()=>window.FiresideCatalog.state==='ready');assert.equal(await page.locator('.shop-card').count(),3);
    await context.clearCookies();await context.addCookies([{name:'fireside_session',value:'user-session',url:base}]);await page.goto(base+'/admin.html');await page.waitForFunction(()=>document.querySelector('#access').textContent.includes('沒有管理權限'));assert.ok(await page.locator('#workspace').isHidden());
    await page.locator('#admin-language').selectOption('en');
    assert.equal(await page.locator('#access').textContent(),'This account does not have administrator access.');
    await page.reload();await page.getByText('This account does not have administrator access.',{exact:true}).waitFor();
    await page.locator('#admin-language').selectOption('zh-TW');
    await page.goto(base+'/index.html');await page.waitForFunction(()=>window.FiresideAccount?.user?.username==='member');assert.equal(await page.locator('#nav-admin').count(),0);
    await page.goto(base+'/shop.html');await page.waitForFunction(()=>window.FiresideAccount?.user?.username==='member');
    await page.locator('.shop-buy[data-bundle="deepsea-duo"]').click();
    await page.getByRole('button',{name:'確認購買',exact:true}).click();
    await page.getByText('購買成功！卡牌已加入「我的卡片」。',{exact:true}).waitFor();
    assert.equal(sqlite.prepare('SELECT coin_balance FROM users WHERE id=2').get().coin_balance,30);
    await page.locator('.purchase-confirm a').click();await page.locator('.owned-card').first().waitFor();
    assert.equal(await page.locator('.owned-card').count(),2);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('.owned-favorite[data-card="25"]').click();
    await page.waitForFunction(()=>document.querySelector('.owned-favorite[data-card="25"]').getAttribute('aria-pressed')==='true');
    await page.locator('#nav-wishlist').click();
    await page.waitForURL('**/favorites.html');
    await page.waitForFunction(()=>document.querySelectorAll('#cards .card').length===1);
    assert.equal(await page.locator('#favorites-only').count(),0);
    assert.equal(await page.locator('#section-heading').textContent(),'我的收藏');
    assert.equal(await page.locator('#nav-wishlist').getAttribute('aria-current'),'page');
    await page.locator('#search').fill('no-matching-favorite');
    assert.equal(await page.locator('#cards .card').count(),0);
    await page.locator('#empty-reset').click();
    assert.equal(await page.locator('#cards .card').count(),1);
    for(const lang of ['en','ja','ko','zh-TW']){await page.selectOption('#language',lang);assert.equal(await page.locator('#cards .card').count(),1);}
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    if(process.env.FAVORITES_SCREENSHOT)await page.screenshot({path:process.env.FAVORITES_SCREENSHOT,fullPage:true});
    await page.route('**/api/favorites',route=>route.fulfill({status:500,body:'{}'}),{times:1});
    await page.reload();
    await page.getByText('收藏載入失敗，請重試',{exact:true}).waitFor();
    assert.equal(await page.locator('#cards .card').count(),0);
    assert.ok(await page.locator('#empty').isHidden());
    await page.getByRole('button',{name:'重新載入收藏',exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('#cards .card').length===1);
    await page.locator('#cards .card').click();
    await page.getByRole('button',{name:'取消收藏',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#favorite-control button').getAttribute('aria-pressed')==='false');
    await page.locator('#close-detail').click();
    await page.getByText('尚無收藏卡牌',{exact:true}).waitFor();
    assert.equal(await page.locator('#cards .card').count(),0);
    assert.ok(await page.locator('#empty-reset').isHidden());
    await page.goto(base+'/index.html');
    await page.waitForFunction(()=>window.FiresideAccount?.user?.username==='member');
    assert.equal(await page.locator('#favorites-only').count(),0);
    await page.locator('#search').fill('');
    await page.evaluate(()=>openDetail('25'));
    await page.getByRole('button',{name:'加入收藏',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#favorite-control button').getAttribute('aria-pressed')==='true');
    await page.goto(base+'/index.html?favorites=1#library');
    await page.waitForURL('**/favorites.html');
    await page.waitForFunction(()=>document.querySelectorAll('#cards .card').length===1);
    const guest=await context.newPage();
    await guest.route('**/api/me',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({user:null})}));
    await guest.goto(base+'/favorites.html');
    await guest.getByText('請登入以查看你的收藏。',{exact:true}).waitFor();
    assert.equal(await guest.locator('#cards .card').count(),0);
    assert.ok(await guest.locator('#empty').isHidden());
    await guest.close();
    assert.equal(await page.locator('#cards .card').count(),1);
    await page.locator('#nav-my-cards').click();await page.locator('.owned-card').first().waitFor();
    await page.locator('.owned-favorite[data-card="25"]').click();
    await page.waitForFunction(()=>document.querySelector('.owned-favorite[data-card="25"]').getAttribute('aria-pressed')==='false');
    assert.equal(await page.locator('.owned-card').count(),2);
    for(const lang of ['en','ja','ko','zh-TW']){await page.selectOption('#language',lang);assert.equal(await page.locator('.owned-card').count(),2);}
    if(process.env.OWNED_SCREENSHOT)await page.screenshot({path:process.env.OWNED_SCREENSHOT,fullPage:true});
    await page.goto(base+'/shop.html');await page.waitForFunction(()=>window.FiresideAccount?.user?.username==='member');
    await page.locator('.shop-buy[data-bundle="deepsea-duo"]').click();
    await page.getByRole('button',{name:'取消',exact:true}).click();
    assert.equal(sqlite.prepare('SELECT coin_balance FROM users WHERE id=2').get().coin_balance,30);
    // The server commits but the response is lost: retry must reuse the key.
    await page.route('**/api/purchases',async route=>{await route.fetch();await route.abort();},{times:1});
    await page.locator('.shop-buy[data-bundle="deepsea-duo"]').click();
    await page.getByRole('button',{name:'確認購買',exact:true}).click();
    await page.getByText('未能確認購買結果，請重試同一筆購買；系統不會重複扣款。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'確認購買',exact:true}).click();
    await page.getByText('購買成功！卡牌已加入「我的卡片」。',{exact:true}).waitFor();
    assert.equal(sqlite.prepare('SELECT coin_balance FROM users WHERE id=2').get().coin_balance,0);
    assert.equal(sqlite.prepare("SELECT quantity FROM user_cards WHERE user_id=2 AND card_id='25'").get().quantity,2);
    await page.getByRole('button',{name:'取消',exact:true}).click();
    await page.locator('.shop-buy[data-bundle="deepsea-duo"]').click();await page.getByRole('button',{name:'確認購買',exact:true}).click();
    await page.getByText('金幣不足，請先加值。',{exact:true}).waitFor();
    await page.getByRole('button',{name:'取消',exact:true}).click();
    sqlite.exec('DROP TABLE catalog_cards; DROP TABLE catalog_products;');
    await page.goto(base+'/index.html');await page.waitForFunction(()=>window.FiresideCatalog.state==='ready');assert.equal(await page.evaluate(()=>window.CARDS.length),31);assert.equal(await page.locator('#cards .card').count(),15);
    await page.goto(base+'/shop.html');await page.waitForFunction(()=>window.FiresideCatalog.state==='ready');assert.equal(await page.locator('.shop-card').count(),3);
    assert.deepEqual(errors,[]);
    console.log('PASS browser -> real handlers -> SQLite: admin catalog, purchases, cancelled checkout, lost response retry, insufficient balance, ownership, wishlist, mobile, four languages and permissions.');
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));sqlite.close();}
})().catch(e=>{console.error(e);process.exit(1);});
