const assert=require('node:assert/strict');
const {database,invoke}=require('./helpers/d1.cjs');
(async()=>{
  const {DB,sqlite}=database();
  const purchase=(await import('../functions/api/purchases.js')).onRequestPost;
  const owned=(await import('../functions/api/my-cards.js')).onRequestGet;
  const favorites=await import('../functions/api/favorites.js');
  const body=(requestId=crypto.randomUUID(),extra={})=>({productId:'deepsea-duo',expectedPrice:30,productVersion:1,requestId,...extra});
  const post=(payload,options={})=>invoke(purchase,DB,{url:'https://cards.test/api/purchases',method:'POST',token:'user-session',body:payload,...options});
  const balance=()=>sqlite.prepare('SELECT coin_balance FROM users WHERE id=2').get().coin_balance;
  const count=table=>sqlite.prepare('SELECT COUNT(*) AS n FROM '+table).get().n;
  assert.equal((await post(body(),{token:null})).status,401);
  assert.equal((await post(body(),{origin:'https://evil.test'})).status,403);
  assert.equal((await post(null)).status,400);
  assert.equal((await post(body(undefined,{expectedPrice:0}))).status,409);
  assert.equal(balance(),60);
  await invoke(favorites.onRequestPut,DB,{method:'PUT',token:'user-session',body:{cardId:'25'}});
  const original=body();const [first,retry]=await Promise.all([post(original),post(original)]);
  assert.equal(first.status,200);assert.equal(retry.status,200);
  assert.equal((await first.json()).orderId,(await retry.json()).orderId);
  assert.equal(balance(),30);assert.equal(count('purchase_orders'),1);assert.equal(count('user_cards'),2);
  assert.equal(count('favorites'),1);assert.equal(count('coin_transactions'),1);
  assert.equal((await post({...original,productId:'inferno-duo'})).status,409);
  await invoke(favorites.onRequestDelete,DB,{method:'DELETE',token:'user-session',body:{cardId:'25'}});
  assert.equal(count('user_cards'),2);
  assert.equal((await post(body())).status,200);assert.equal(balance(),0);
  assert.equal(sqlite.prepare("SELECT quantity FROM user_cards WHERE user_id=2 AND card_id='25'").get().quantity,2);
  const n=count('purchase_orders');assert.equal((await post(body())).status,409);assert.equal(count('purchase_orders'),n);
  assert.equal((await (await invoke(owned,DB,{token:'admin-session'})).json()).cards.length,0);
  sqlite.exec("UPDATE catalog_cards SET status='archived' WHERE id='25';UPDATE users SET coin_balance=60 WHERE id=2;");
  assert.equal((await post(body())).status,409);
  const held=await (await invoke(owned,DB,{token:'user-session'})).json();assert.equal(held.cards.length,2);
  assert.equal(held.cards.find(row=>row.card.id==='25').quantity,2);
  sqlite.exec("UPDATE catalog_cards SET status='active' WHERE id='25';UPDATE catalog_products SET version=2,data=json_set(data,'$.coinPrice',40) WHERE id='deepsea-duo';");
  assert.equal((await post(body())).status,409);
  assert.equal((await post(original)).status,200);assert.equal(balance(),60); // retry old order, no reprice/debit
  sqlite.exec("CREATE TRIGGER fail_delivery BEFORE UPDATE ON user_cards BEGIN SELECT RAISE(ABORT,'delivery-failed'); END;");
  await assert.rejects(()=>post(body(undefined,{expectedPrice:40,productVersion:2})),/delivery-failed/);
  assert.equal(balance(),60);assert.equal(count('purchase_orders'),n);assert.equal(count('coin_transactions'),2);
  sqlite.exec('DROP TRIGGER fail_delivery');
  const competing=await Promise.all([post(body(undefined,{expectedPrice:40,productVersion:2})),post(body(undefined,{expectedPrice:40,productVersion:2}))]);
  assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);assert.equal(balance(),20);
  const snapshot=sqlite.prepare('SELECT cards_snapshot,total FROM purchase_orders ORDER BY rowid LIMIT 1').get();assert.equal(snapshot.total,30);assert.equal(JSON.parse(snapshot.cards_snapshot).length,2);
  sqlite.close();console.log('PASS purchases: auth, CSRF, server price, replay protection, concurrent balance, atomic rollback, quantity, wishlist independence, user isolation and archived ownership.');
})().catch(e=>{console.error(e);process.exitCode=1;});
